version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik_nii
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - "8081:80"
      - "8082:8080" # dashboard: http://localhost:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: laravel_backend
    environment:
      PHP_MEMORY_LIMIT: 512M
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    command: php artisan serve --host=0.0.0.0 --port=8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`nii.test`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - appnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: nii_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.nii.test`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    depends_on:
      - backend
    networks:
      - appnet
      
  mysql:
    image: mysql:8.0
    container_name: mysql_nii
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nii_db
      MYSQL_USER: nii
      MYSQL_PASSWORD: nii123
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"   # host port 3307 -> mysql inside 3306
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mysql_data: